import streamlit as st
import json
import pandas as pd
from pathlib import Path
import os
from PIL import Image

# Page Config
st.set_page_config(
    page_title="UIDAI Intelligence System",
    page_icon="🇮🇳",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom Styling
st.markdown("""
<style>
    .main {
        background-color: #f8f9fa;
    }
    .stMetric {
        background-color: white;
        padding: 15px;
        border-radius: 10px;
        box-shadow: 2px 2px 10px rgba(0,0,0,0.05);
    }
    h1, h2, h3 {
        color: #2c3e50;
    }
</style>
""", unsafe_allow_html=True)

# Title
st.title("🇮🇳 UIDAI Intelligence System")
st.markdown("**Production-Ready Analytical & Predictive Platform**")

# Sidebar
st.sidebar.header("System Controls")
st.sidebar.info("This dashboard visualizes the latest intelligence report generated by the UIDAI Intelligence Engine.")

# Load latest report
@st.cache_data
def load_latest_report():
    report_dir = Path("outputs/reports")
    if not report_dir.exists():
        return None
    
    json_files = list(report_dir.glob("*.json"))
    if not json_files:
        return None
        
    # Get latest file
    latest_file = max(json_files, key=os.path.getctime)
    with open(latest_file, 'r') as f:
        return json.load(f)

report = load_latest_report()

if not report:
    st.error("No reports found! Please run the analysis pipeline first.")
    st.stop()

# Dashboard Layout
col1, col2, col3, col4 = st.columns(4)

dri = report['data_governance']['dri']
geo = report['descriptive_analytics']['geographic_patterns']
anomalies = report['anomaly_detection']['summary']
policy = report['policy_impact']

with col1:
    st.metric("Data Reliability Index", f"{dri['dri_score']}", delta=dri['assessment'])

with col2:
    st.metric("Total Enrollments", f"{report['metadata']['data_records']:,}")

with col3:
    st.metric("Anomalies Detected", f"{anomalies['total_anomalies']:,}", delta_color="inverse")

with col4:
    st.metric("Critical Districts", f"{policy['resource_allocation']['critical_districts']}", delta="Action Req", delta_color="inverse")

# Tabs for Sections
tab1, tab2, tab3, tab4, tab5 = st.tabs([
    "📈 Trends & Demographics", 
    "🔍 Anomaly Detection", 
    "🔮 Forecast", 
    "🛡️ Policy Impact",
    "📝 Raw Data"
])

vis_dir = Path("outputs/visualizations")

def show_image(filename, caption):
    path = vis_dir / filename
    if path.exists():
        st.image(str(path), caption=caption, use_container_width=True)
    else:
        st.warning(f"Plot {filename} not found.")

with tab1:
    col_a, col_b = st.columns(2)
    with col_a:
        st.subheader("Enrollment Trends")
        show_image("temporal_trend.png", "Monthly Trends")
    with col_b:
        st.subheader("Demographics")
        show_image("age_distribution.png", "Age Distribution")
        
    st.info(f"Geographic Coverage: {geo['coverage']['num_states']} States, {geo['coverage']['num_districts']} Districts")

with tab2:
    col_a, col_b = st.columns([2, 1])
    with col_a:
        st.subheader("Anomaly Severity")
        show_image("anomaly_severity.png", "Severity Distribution")
    with col_b:
        st.subheader("Detection Summary")
        st.table(pd.DataFrame({
            "Method": ["Statistical", "Temporal", "Geographic", "ML-Based"],
            "Count": [
                anomalies['statistical_anomalies'],
                anomalies['temporal_anomalies'],
                anomalies['geographic_anomalies'],
                anomalies['ml_anomalies']
            ]
        }))

with tab3:
    st.subheader("6-Month Enrollment Forecast")
    show_image("forecast_plot.png", "Predictive Modeling with Confidence Intervals")
    
    surge = report['forecasting']['surge_detection']
    if surge['surge_detected']:
        st.error(f"⚠️ SURGE DETECTED: {surge['num_surge_periods']} period(s) of high demand expected.")
    else:
        st.success("✅ Demand Stability: No enrollment surges predicted.")

with tab4:
    col_a, col_b = st.columns(2)
    with col_a:
        st.subheader("Resource Allocation")
        show_image("policy_impact.png", "Intervention Needs")
    with col_b:
        st.subheader("Strategic Recommendations")
        for i, rec in enumerate(policy['strategic_recommendations'], 1):
            st.write(f"{i}. {rec}")
            
    st.warning(f"Resource Requirements: {policy['resource_allocation']['total_required_centers']:,} Centers, {policy['resource_allocation']['total_required_staff']:,} Staff")

with tab5:
    st.json(report)

# Footer
st.markdown("---")
st.caption(f"Generated by UIDAI Intelligence System v{report['metadata'].get('version', '1.0')} | {report['metadata']['generated_at']}")
